language: generic
dist: xenial

services:
  - docker

before_install:
  - docker load --input $HOME/docker-cache/our-image.tar qgis-desktop || true

install:
  - docker-compose build

script:
  # We set the QT_QPA_PLATFORM to run the tests on a headless server:
  # http://doc.qt.io/qt-5/embedded-linux.html
  - docker-compose run -e QT_QPA_PLATFORM=offscreen qgis-desktop make test
  - docker-compose run qgis-desktop make pep8

before_cache:
  - mkdir -p $HOME/docker-cache
  - docker save --output $HOME/docker-cache/our-image.tar qgis-desktop

notifications:
  email: false
