language: generic
dist: xenial

env:
    - UID=1000 USER=qgis_user

services:
  - docker

before_install:
  - cd Docker/base
  - ls -la
  - docker build -t qgis-desktop:base .
  - cd ../..
  - docker-compose build

script:
    - docker-compose run qgis-desktop make test
    - docker-compose run qgis-desktop make pep8

notifications:
    email: false