language: generic
dist: xenial

env:
    - UID=1000 USER=qgis_user

services:
  - docker

before_install:
  - cd Docker/base
  - ls -la
  - docker build -t qgis-desktop:base .
  - cd ../..
  - docker-compose build

script:
    # this script adds standard qgis plugins (like db_manager) to PYTHONPATH
    # - source scripts/run-env-linux.sh /usr
    - docker run qgis:3.4 make test
    - docker run qgis:3.4 make pep8

notifications:
    email: false