language: generic
dist: xenial

services:
  - docker

cache:
  directories:
    - $HOME/docker-cache

before_install:
  # If the docker checksum matches, use the cached docker image.
  - >
     md5sum --check $HOME/docker-cache/docker-checksum &&
     cat $HOME/docker-cache/our-image.tar | docker load || true

install:
  # Rebuild the docker image, but only if the docker checksum does not match.
  - >
     md5sum --check $HOME/docker-cache/docker-checksum ||
     docker-compose build --build-arg uid=`id -u` --build-arg gid=`id -g`

script:
  # We set the QT_QPA_PLATFORM to run the tests on a headless server:
  # http://doc.qt.io/qt-5/embedded-linux.html
  - docker-compose run -e QT_QPA_PLATFORM=offscreen qgis-desktop make test
  - docker-compose run qgis-desktop make pep8

before_cache:
  # If the docker checksum did not match, save the new docker image + checksum.
  - mkdir -p $HOME/docker-cache
  - >
     md5sum --check $HOME/docker-cache/docker-checksum || docker save
     qgis-desktop > $HOME/docker-cache/our-image.tar
  - >
     md5sum --check $HOME/docker-cache/docker-checksum || scripts/create-travis-checksum.sh

notifications:
  email: false
