language: generic
dist: xenial

env:
    - UID=1000 USER=qgis_user

services:
  - docker

addons:
  apt:
    packages:
      - xvfb  # emulating X-server

before_install:
  - cd Docker/base
  - ls -la
  - docker build -t qgis-desktop:base .
  - cd ../..
  - docker-compose build

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - docker-compose run qgis-desktop make test
  - docker-compose run qgis-desktop make pep8

notifications:
    email: false