language: generic
dist: xenial

services:
  - docker

cache:
  directories:
    - $HOME/docker-cache

before_install:
  - cat $HOME/docker-cache/our-image.tar | docker load || true

# install:
#   - docker-compose build

script:
  # We set the QT_QPA_PLATFORM to run the tests on a headless server:
  # http://doc.qt.io/qt-5/embedded-linux.html
  - docker-compose run -e QT_QPA_PLATFORM=offscreen qgis-desktop make test
  - docker-compose run qgis-desktop make pep8

before_cache:
  - mkdir -p $HOME/docker-cache
  - docker save qgis-desktop > $HOME/docker-cache/our-image.tar

notifications:
  email: false
