version: '3.0'

services:

  qgis-desktop:
    image: qgis-desktop:3.4
    build:
      context: Docker/qgis3
      dockerfile: Dockerfile
      args:
        QGIS_VERSION: 3.4  # Not used currently
        USER_ID: ${UID}
        GROUP_ID: ${UID}
        USER_NAME: ${USER}
    volumes:
      - ${HOME}/.local/share/QGIS:/home/${USER}/.local/share/QGIS
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/home/${USER}/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ThreeDiToolbox
      - ${HOME}/.local/share/QGIS/QGIS3/profiles/default/python/plugins/:/home/${USER}/.local/share/QGIS/QGIS3/profiles/default/python/plugins/
      - /home/richard/Programs/pycharm-2018.1.2/debug-eggs/:/srv/eggs/debug-eggs/
    environment:
      - USER_NAME=${USER}
      - USER_ID=${UID}
      - GROUP_ID=${UID}
      - DISPLAY=unix${DISPLAY}
    working_dir: /home/${USER}/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ThreeDiToolbox

# TODO: once we have a QGIS2 and QGIS3 (master) branch, we can have one
#  docker-compose.yml file.